[package]
name = "future"
version = "0.3.0"
authors = ["KizzyCode Software Labs./Keziah Biermann <development@kizzycode.de>"]
description = "This library provides spin-loop-free futures and a helper functions to run a job asynchronously."
license = "BSD-2-Clause OR MIT"
repository = "https://github.com/KizzyCode/future"
readme = "README.md"

[dependencies]
etrace = "0.2.8"